version: "3.9"
services:
  app:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: ["gpu"]
              count: "all"
    ports:
      - "7860:7860"
    volumes:
      - ".:/workspace"
